language: java
git:
  depth: 1
jdk:
  - openjdk8
dist: trusty
cache:
  directories:
    - $HOME/.m2

deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  username: sid-ahmed.imloul@dauphine.eu
  password: $BLUEMIX_PASSWORD
  organization: sid-ahmed.imloul@dauphine.eu
  space: dev
  region: eu-gb


